basePath: /api/v1
info:
  contact: {}
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /newcommodity:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 新增商品
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: Cate_ID
        in: formData
        name: cate_id
        required: true
        type: integer
      - description: 數量
        in: formData
        name: amount
        required: true
        type: integer
      - description: Price
        in: formData
        name: price
        required: true
        type: integer
      - description: title
        in: formData
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 新增
      tags:
      - New
swagger: "2.0"
