basePath: /api/v1
info:
  contact: {}
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /newcommodity:
    post:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: ID
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show an account
      tags:
      - accounts
swagger: "2.0"
